publish_rate: 200.0
accel_odr: 0x0C    # BMI160_ACCEL_ODR_1600HZ
accel_range: 0x05  # BMI160_ACCEL_RANGE_4G
accel_bw: 0x02     # BMI160_ACCEL_BW_NORMAL_AVG4
gyro_odr: 0x0D     # BMI160_GYRO_ODR_3200HZ
gyro_range: 0x00   # BMI160_GYRO_RANGE_2000_DPS
gyro_bw: 0x02      # BMI160_GYRO_BW_NORMAL_MODE
imu_frame_id: "imu_link"
